config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }

  root 'posts#index', as: 'home'

  resources :posts do
    resources :comments
    member do
        put "like" => "posts#upvote"
        put "dislike" => "posts#downvote"
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy

acts_as_voter
has_many :comments, dependent: :destroy
has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]
has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    #user.name = auth.info.name   # assuming the user model has a name
   # user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :admin
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
acts_as_votable
has_attached_file :avatar
has_many :comments, dependent: :destroy
belongs_to :admin
validates :title, presence: true,
                    length: {minimum: 5}
validates_format_of :date, :with => /\d{2}\/\d{2}\/\d{4}/, :message => "must be in the following format: dd/mm/yyyy"

has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/admins/omniauth_callbacks_controller.rb
class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = Admin.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_admin_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_admin!, except: [:index]
    
    def new
        @comment = current_admin.comments.build
    end
    
    def create
        @comment = current_admin.comments.build(comment_params)
        @post = Post.find(params[:post_id])
        @comment.post_id = @post.id
        @comment.save
        redirect_to post_path(@post)
    end
    
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end
    
    private def comment_params
        params.require(:comment).permit(:body, :post_id, :admin_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_admin!, except: [:index]
    def index
        @posts = Post.all
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def new 
        @post = Post.new
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    
    def update
        @post = Post.find(params[:id])
        
        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end
    
    def create
        @post = Post.new(post_params)
        @post.admin_id = current_admin.id
        
        if(@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end
    
    def upvote
        @post = Post.find(params[:id])
        @post.upvote_from current_admin
        redirect_to @post
    end
    
    def downvote
        @post = Post.find(params[:id])
        @post.downvote_from current_admin
        redirect_to @post
    end
    
    private def post_params
        params.require(:post).permit(:body, :title, :date, :admin_id, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Komentarji</h3>
<% @post.comments.each do |comment| %>
    <div class='card p-3'>
    <b><%= comment.admin.try(:email) %></b><br>
    <p><%= comment.body %></p>
    <% if comment.admin_id == current_admin.id %>
    <div class="text-right"><%= link_to "Izbriši", [comment.post, comment],
                            method: :delete,
                            data: {confirm: 'Ali ste prepričani?'},
                            :class => 'btn btn-danger' %></div>
    </div>
<% end %><% end %>

app/views/comments/_form.html.erb
<h3>Dodaj komentar</h3>
<%= form_for ([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :Komentar %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
 
  <p>
    <%= f.submit({:class => 'btn btn-md btn-outline-primary'}) %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Malice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand text-white">MALICE</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Domov", home_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav navbar-right">
            <% if admin_signed_in? %>
        <!--This block is only visible to signed in admins -->
        
       <li class="nav-item"><%= link_to "Dodaj malico", new_post_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to 'Moj račun', edit_admin_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"><%= link_to 'Odjava', destroy_admin_session_path, :method => :delete, class: "nav-link" %></li>
        <!-- The block ends here -->
        <% else %>
          <li class="nav-item"><%= link_to "Prijava", new_admin_session_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Sign in with Google", admin_google_oauth2_omniauth_authorize_path, class: "nav-link" %></li>
        <% end %>
      </div>
    </nav>


<main role="main" class="container">

    <div class="starter-template">
<%= yield %>
    </div>

</main><!-- /.container -->

</body>
</html>

app/views/posts/edit.html.erb
<h1 class='mt-3'>Uredi malico</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <div class='alert alert-danger'><%= msg %></div>
  <% end %>
<% end %>
  <p>
    <%= f.label :Naslov %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
 
  <p>
    <%= f.label :Opis %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>
  
  <p>
    <%= f.label :Datum %><br>
    <%= f.text_field(:date, {:class => 'form-control'}) %>
  </p>
 
  <p>
    <%= f.submit({:class => 'btn btn-md btn-outline-primary'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1 class='mt-2 text-center'><b>Malice</b></h1>
<% @posts.each do |post| %>
    <div class='card mt-4 p-3'>
        <h2><%= post.title %></h2>
        <div><%= post.body %></div>
        <div class='text-right'>Datum malice: <%= post.date %></div>
        <div class='text-right'><% if current_admin.voted_up_on? post %>Na to malico <b>ste</b> prijavljeni
        <% else %>Na to malico <b>niste</b> prijavljeni<% end %></div>
        <div>
        <%= link_to "Podrobnosti", post_path(post), :class => 'btn btn-secondary' %></div>
        </div>
<% end %>

app/views/posts/new.html.erb
<h1 class='mt-3'>Nova malica</h1>
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <div class='alert alert-danger'><%= msg %></div>
  <% end %>
<% end %>
  <p>
    <%= f.label :Naslov %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>
 
  <p>
    <%= f.label :Opis %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :Datum %><br>
    <%= f.text_field(:date, {:class => 'form-control'}) %>
  </p>
  
  <p>
    <%= f.label :Slika %><br>
    <%= f.file_field :avatar %>
  </p>
  
  <p>
    <%= f.submit({:class => 'btn btn-md btn-outline-primary'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1 class='mt-3 text-center'><b><%= @post.title %></b></h1>

<div class='mt-3 text-center'><%= image_tag @post.avatar.url(:medium) %></div>

<div class='mt-2 text-center'><%= @post.body %></div>

<div class='mt-2 text-right'>Datum malice: <b><%= @post.date %></b></div>
<hr>
<div class='mt-2'><%= link_to "Prijava na malico", like_post_path(@post), method: :put, :class => 'btn btn-primary' %>
<%= link_to "Odjava iz malice", dislike_post_path(@post), method: :put, :class => 'btn btn-danger' %></div>

<div class='mt-2'><% if current_admin.voted_up_on? @post %>Na malico <b>ste</b> prijavljeni
<% else %>Na malico <b>niste</b> prijavljeni<% end %></div>

<div class='mt-2'>Na malice sem se prijavil že:  <b><%= current_admin.find_liked_items.size %></b></div>

<div class='mt-4 text-right'><br><%= link_to "Uredi", edit_post_path(@post), :class => 'btn btn-primary' %>
<%= link_to "Izbriši", post_path(@post), 
                        method: :delete,
                        data: {confirm: 'Ali ste prepričani?'},
                        :class => 'btn btn-danger' %></div> 
<hr>

<%= render 'comments/form' %>
<hr>
<%= render 'comments/comments' %>